title: IRSTD-Arxiv-Daily
description: Automatically Update CV Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/Fortuneteller6/IRSTD-Arxiv-Daily
  another_url: https://github.com/Fortuneteller6/IRSTD-Arxiv-Daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: Fortuneteller6

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
